import { useCallback,useEffect,useState,type FormEvent } from "react";
import api from "../api/api";
import type { Escala,ItemEscala } from "./Escalas";
import type { Indisponibilidade,TipoIndisponibilidade } from "./Indisponibilidades";
import type { SolicitacaoTroca } from "./TrocasTurno";
import "./PortalBombeiro.css";

interface Props{usuario:{nome:string;email:string;bombeiroId:number|null};aoSair:()=>void}
interface Opcao{id:number;nomeCompleto:string;equipe:string|null}
const tipos:Array<[TipoIndisponibilidade,string]>=[["FERIAS","Férias"],["FOLGA","Folga"],["LICENCA","Licença"],["AFASTAMENTO","Afastamento"],["COMPROMISSO","Compromisso"],["OUTRO","Outro"]];
const nomesStatus:Record<string,string>={AGUARDANDO_ACEITE:"Aguardando aceite",AGUARDANDO_APROVACAO:"Aguardando aprovação",APROVADA:"Aprovada",RECUSADA:"Recusada",CANCELADA:"Cancelada"};
const data=(v:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short"}).format(new Date(`${v}T00:00:00`));
const dataHora=(v:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v));

export default function PortalBombeiro({usuario,aoSair}:Props){
 const [tela,setTela]=useState<"inicio"|"escala"|"indisponibilidades"|"trocas">("inicio");
 const [escalas,setEscalas]=useState<Escala[]>([]); const [indisponibilidades,setIndisponibilidades]=useState<Indisponibilidade[]>([]);
 const [trocas,setTrocas]=useState<SolicitacaoTroca[]>([]); const [opcoes,setOpcoes]=useState<Opcao[]>([]);
 const [formAberto,setFormAberto]=useState(false); const [turnoTroca,setTurnoTroca]=useState<ItemEscala|null>(null);
 const [substitutoId,setSubstitutoId]=useState(""); const [motivoTroca,setMotivoTroca]=useState("");
 const [tipo,setTipo]=useState<TipoIndisponibilidade>("FOLGA"); const [inicio,setInicio]=useState(""); const [fim,setFim]=useState("");
 const [motivo,setMotivo]=useState(""); const [negociavel,setNegociavel]=useState(true); const [erro,setErro]=useState(""); const [carregando,setCarregando]=useState(true);
 const carregar=useCallback(async()=>{try{setCarregando(true);setErro("");const [a,b,c,d]=await Promise.all([api.get<Escala[]>("/me/schedules"),api.get<Indisponibilidade[]>("/me/unavailabilities"),api.get<SolicitacaoTroca[]>("/me/shift-exchanges"),api.get<Opcao[]>("/me/firefighters")]);setEscalas(a.data);setIndisponibilidades(b.data);setTrocas(c.data);setOpcoes(d.data)}catch{setErro("Não foi possível carregar seus dados.")}finally{setCarregando(false)}},[]);
 useEffect(()=>{void carregar()},[carregar]);
 async function salvar(e:FormEvent){e.preventDefault();if(fim<inicio){setErro("A data final não pode ser anterior à inicial.");return}try{await api.post("/me/unavailabilities",{tipo,dataInicio:inicio,dataFim:fim,negociavel:tipo==="FERIAS"?false:negociavel,motivo:motivo.trim()||null});setFormAberto(false);setInicio("");setFim("");setMotivo("");await carregar()}catch(x:any){setErro(x.response?.data?.message??"Não foi possível registrar.")}}
 async function excluir(id:number){if(!confirm("Deseja excluir esta indisponibilidade?"))return;try{await api.delete(`/me/unavailabilities/${id}`);await carregar()}catch{setErro("Não foi possível excluir o registro.")}}
 async function solicitarTroca(e:FormEvent){e.preventDefault();if(!turnoTroca||!substitutoId)return;try{await api.post("/me/shift-exchanges",{itemEscalaId:turnoTroca.id,substitutoId:Number(substitutoId),motivo:motivoTroca.trim()||null});setTurnoTroca(null);setSubstitutoId("");setMotivoTroca("");setTela("trocas");await carregar()}catch(x:any){setErro(x.response?.data?.message??"Não foi possível solicitar a troca.")}}
 async function responder(id:number,aceitar:boolean){try{await api.patch(`/me/shift-exchanges/${id}/response`,null,{params:{aceitar}});await carregar()}catch(x:any){setErro(x.response?.data?.message??"Não foi possível responder.")}}
 const plantoes=escalas.flatMap(escala=>escala.itens.map(item=>({...item,escala:escala.nome})));
 return <div className="portal-layout"><aside className="portal-sidebar"><div className="portal-brand"><span>🔥</span><div><strong>EscalaFácil</strong><small>Portal do bombeiro</small></div></div><nav><button className={tela==="inicio"?"active":""} onClick={()=>setTela("inicio")}>▦ Início</button><button className={tela==="escala"?"active":""} onClick={()=>setTela("escala")}>▣ Minha escala</button><button className={tela==="trocas"?"active":""} onClick={()=>setTela("trocas")}>⇄ Trocas</button><button className={tela==="indisponibilidades"?"active":""} onClick={()=>setTela("indisponibilidades")}>! Indisponibilidades</button></nav><div className="portal-user"><strong>{usuario.nome}</strong><small>{usuario.email}</small><button onClick={aoSair}>Sair</button></div></aside>
 <main className="portal-content"><header><div><span>ÁREA DO BOMBEIRO</span><h1>{tela==="escala"?"Minha escala":tela==="trocas"?"Trocas de turno":tela==="indisponibilidades"?"Minhas indisponibilidades":`Olá, ${usuario.nome.split(" ")[0]}`}</h1></div></header>{erro&&<div className="portal-error">{erro}</div>}{carregando?<div className="portal-empty">Carregando...</div>:tela==="inicio"?<><section className="portal-cards"><article><span>Próximos plantões</span><strong>{plantoes.filter(p=>!p.cancelado).length}</strong><small>em escalas publicadas</small></article><article><span>Trocas em andamento</span><strong>{trocas.filter(t=>t.status.startsWith("AGUARDANDO")).length}</strong><small>solicitações abertas</small></article></section><section className="portal-panel"><h2>Próximos plantões</h2>{plantoes.length?plantoes.slice(0,5).map(p=><div className="portal-row" key={p.id}><div><strong>{p.escala}</strong><small>{dataHora(p.inicioPlantao)} até {dataHora(p.fimPlantao)}</small></div><span>{p.cancelado?"Cancelado":"Confirmado"}</span></div>):<p>Nenhum plantão publicado para você.</p>}</section></>:tela==="escala"?<section className="portal-panel"><h2>Escalas publicadas</h2>{escalas.length?escalas.map(e=><article className="portal-schedule" key={e.id}><div><strong>{e.nome}</strong><small>{data(e.dataInicio)} a {data(e.dataFim)}</small></div>{e.itens.map(i=><div className="portal-shift" key={i.id}><span>{dataHora(i.inicioPlantao)} — {dataHora(i.fimPlantao)}</span>{i.cancelado?<strong>Cancelado: {i.motivoCancelamento}</strong>:<button onClick={()=>setTurnoTroca(i)}>Solicitar troca</button>}</div>)}</article>):<p>Nenhuma escala publicada para você.</p>}</section>:tela==="trocas"?<section className="portal-panel"><h2>Solicitações</h2>{trocas.length?trocas.map(t=><div className="portal-row" key={t.id}><div><strong>{t.solicitanteNome} → {t.substitutoNome}</strong><small>{t.escalaNome} · {dataHora(t.inicioPlantao)} · {nomesStatus[t.status]}</small></div>{t.substitutoId===usuario.bombeiroId&&t.status==="AGUARDANDO_ACEITE"&&<div><button onClick={()=>void responder(t.id,true)}>Aceitar</button><button className="portal-delete" onClick={()=>void responder(t.id,false)}>Recusar</button></div>}</div>):<p>Nenhuma solicitação.</p>}</section>:<section className="portal-panel"><div className="portal-panel-title"><div><h2>Períodos informados</h2><p>Avise quando não puder participar da escala.</p></div><button onClick={()=>setFormAberto(true)}>+ Registrar</button></div>{indisponibilidades.length?indisponibilidades.map(i=><div className="portal-row" key={i.id}><div><strong>{tipos.find(([v])=>v===i.tipo)?.[1]}</strong><small>{data(i.dataInicio)} a {data(i.dataFim)} · {i.motivo||"Sem observação"}</small></div><button className="portal-delete" onClick={()=>void excluir(i.id)}>Excluir</button></div>):<p>Nenhuma indisponibilidade registrada.</p>}</section>}</main>
 {formAberto&&<div className="portal-modal" onMouseDown={()=>setFormAberto(false)}><form onSubmit={salvar} onMouseDown={e=>e.stopPropagation()}><h2>Nova indisponibilidade</h2><label>Tipo<select value={tipo} onChange={e=>setTipo(e.target.value as TipoIndisponibilidade)}>{tipos.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><div className="portal-dates"><label>Início<input required type="date" value={inicio} onChange={e=>setInicio(e.target.value)}/></label><label>Fim<input required min={inicio} type="date" value={fim} onChange={e=>setFim(e.target.value)}/></label></div><label className="portal-check"><input type="checkbox" checked={negociavel} disabled={tipo==="FERIAS"} onChange={e=>setNegociavel(e.target.checked)}/> Pode ser negociada</label><label>Observação<textarea value={motivo} onChange={e=>setMotivo(e.target.value)}/></label><div className="portal-form-actions"><button type="button" onClick={()=>setFormAberto(false)}>Cancelar</button><button type="submit">Registrar</button></div></form></div>}
 {turnoTroca&&<div className="portal-modal" onMouseDown={()=>setTurnoTroca(null)}><form onSubmit={solicitarTroca} onMouseDown={e=>e.stopPropagation()}><h2>Solicitar troca</h2><p>{dataHora(turnoTroca.inicioPlantao)}</p><label>Substituto<select required value={substitutoId} onChange={e=>setSubstitutoId(e.target.value)}><option value="">Selecione</option>{opcoes.filter(o=>o.id!==usuario.bombeiroId).map(o=><option key={o.id} value={o.id}>{o.nomeCompleto}{o.equipe?` — ${o.equipe}`:""}</option>)}</select></label><label>Motivo<textarea maxLength={255} value={motivoTroca} onChange={e=>setMotivoTroca(e.target.value)}/></label><div className="portal-form-actions"><button type="button" onClick={()=>setTurnoTroca(null)}>Cancelar</button><button type="submit">Enviar solicitação</button></div></form></div>}</div>
}
