spring:

  config:
    import: optional:file:.env[.properties]

  application:
    name: escala-facil-bombeiros

  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5434/escala_facil}
    username: ${DB_USERNAME:escala_user}
    password: ${DB_PASSWORD}

server:
  port: 8082
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: "RXNjYWxhRmFjaWxCb21iZWlyb3NTZWdyZWRvMjAyNlNlZ3Vybw=="
    expiration: 28800000
  admin:
    nome: ${ADMIN_NAME:Administrador}
    email: ${ADMIN_EMAIL:}
    senha: ${ADMIN_PASSWORD:}